/* valatyperegisterfunction.c generated by valac, the Vala compiler
 * generated from valatyperegisterfunction.vala, do not modify */

/* valatyperegisterfunction.vala
 *
 * Copyright (C) 2006-2010  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <stdlib.h>
#include <string.h>
#include <valaccode.h>
#include <valagee.h>
#include <gobject/gvaluecollector.h>


#define VALA_TYPE_TYPEREGISTER_FUNCTION (vala_typeregister_function_get_type ())
#define VALA_TYPEREGISTER_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_TYPEREGISTER_FUNCTION, ValaTypeRegisterFunction))
#define VALA_TYPEREGISTER_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_TYPEREGISTER_FUNCTION, ValaTypeRegisterFunctionClass))
#define VALA_IS_TYPEREGISTER_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_TYPEREGISTER_FUNCTION))
#define VALA_IS_TYPEREGISTER_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_TYPEREGISTER_FUNCTION))
#define VALA_TYPEREGISTER_FUNCTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_TYPEREGISTER_FUNCTION, ValaTypeRegisterFunctionClass))

typedef struct _ValaTypeRegisterFunction ValaTypeRegisterFunction;
typedef struct _ValaTypeRegisterFunctionClass ValaTypeRegisterFunctionClass;
typedef struct _ValaTypeRegisterFunctionPrivate ValaTypeRegisterFunctionPrivate;
#define _vala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_node_unref (var), NULL)))
#define _vala_code_context_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_context_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
typedef struct _ValaParamSpecTypeRegisterFunction ValaParamSpecTypeRegisterFunction;

struct _ValaTypeRegisterFunction {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ValaTypeRegisterFunctionPrivate * priv;
};

struct _ValaTypeRegisterFunctionClass {
	GTypeClass parent_class;
	void (*finalize) (ValaTypeRegisterFunction *self);
	ValaTypeSymbol* (*get_type_declaration) (ValaTypeRegisterFunction* self);
	gchar* (*get_type_struct_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_base_init_func_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_class_finalize_func_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_base_finalize_func_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_class_init_func_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_instance_struct_size) (ValaTypeRegisterFunction* self);
	gchar* (*get_instance_init_func_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_parent_type_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_gtype_value_table_init_function_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_gtype_value_table_peek_pointer_function_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_gtype_value_table_free_function_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_gtype_value_table_copy_function_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_gtype_value_table_lcopy_value_function_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_gtype_value_table_collect_value_function_name) (ValaTypeRegisterFunction* self);
	gchar* (*get_type_flags) (ValaTypeRegisterFunction* self);
	ValaCCodeFragment* (*get_type_interface_init_declaration) (ValaTypeRegisterFunction* self);
	void (*get_type_interface_init_statements) (ValaTypeRegisterFunction* self, ValaCCodeBlock* block, gboolean plugin);
	ValaSymbolAccessibility (*get_accessibility) (ValaTypeRegisterFunction* self);
};

struct _ValaTypeRegisterFunctionPrivate {
	ValaCCodeFragment* source_declaration_fragment;
	ValaCCodeFragment* declaration_fragment;
	ValaCCodeFragment* definition_fragment;
	ValaCodeContext* _context;
};

struct _ValaParamSpecTypeRegisterFunction {
	GParamSpec parent_instance;
};


static gpointer vala_typeregister_function_parent_class = NULL;

gpointer vala_typeregister_function_ref (gpointer instance);
void vala_typeregister_function_unref (gpointer instance);
GParamSpec* vala_param_spec_typeregister_function (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void vala_value_set_typeregister_function (GValue* value, gpointer v_object);
void vala_value_take_typeregister_function (GValue* value, gpointer v_object);
gpointer vala_value_get_typeregister_function (const GValue* value);
GType vala_typeregister_function_get_type (void) G_GNUC_CONST;
#define VALA_TYPEREGISTER_FUNCTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), VALA_TYPE_TYPEREGISTER_FUNCTION, ValaTypeRegisterFunctionPrivate))
enum  {
	VALA_TYPEREGISTER_FUNCTION_DUMMY_PROPERTY
};
void vala_typeregister_function_init_from_type (ValaTypeRegisterFunction* self, gboolean plugin, gboolean declaration_only);
ValaTypeSymbol* vala_typeregister_function_get_type_declaration (ValaTypeRegisterFunction* self);
gchar* vala_ccode_base_module_get_ccode_lower_case_name (ValaCodeNode* node, const gchar* infix);
ValaSymbolAccessibility vala_typeregister_function_get_accessibility (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_gtype_value_table_init_function_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_gtype_value_table_free_function_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_gtype_value_table_copy_function_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_gtype_value_table_peek_pointer_function_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_gtype_value_table_collect_value_function_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_gtype_value_table_lcopy_value_function_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_base_finalize_func_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_type_struct_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_base_init_func_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_class_init_func_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_class_finalize_func_name (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_instance_struct_size (ValaTypeRegisterFunction* self);
gchar* vala_typeregister_function_get_instance_init_func_name (ValaTypeRegisterFunction* self);
ValaCCodeFragment* vala_typeregister_function_get_type_interface_init_declaration (ValaTypeRegisterFunction* self);
ValaCodeContext* vala_typeregister_function_get_context (ValaTypeRegisterFunction* self);
gchar* vala_ccode_base_module_get_ccode_name (ValaCodeNode* node);
gchar* vala_typeregister_function_get_parent_type_name (ValaTypeRegisterFunction* self);
gchar* vala_ccode_base_module_get_ccode_dup_function (ValaTypeSymbol* sym);
gchar* vala_ccode_base_module_get_ccode_free_function (ValaTypeSymbol* sym);
ValaCCodeConstant* vala_ccode_base_module_get_enum_value_canonical_cconstant (ValaEnumValue* ev);
gchar* vala_typeregister_function_get_type_flags (ValaTypeRegisterFunction* self);
void vala_typeregister_function_get_type_interface_init_statements (ValaTypeRegisterFunction* self, ValaCCodeBlock* block, gboolean plugin);
static ValaTypeSymbol* vala_typeregister_function_real_get_type_declaration (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_type_struct_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_base_init_func_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_class_finalize_func_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_base_finalize_func_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_class_init_func_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_instance_struct_size (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_instance_init_func_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_parent_type_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_init_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_peek_pointer_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_free_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_copy_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_lcopy_value_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_gtype_value_table_collect_value_function_name (ValaTypeRegisterFunction* self);
static gchar* vala_typeregister_function_real_get_type_flags (ValaTypeRegisterFunction* self);
static ValaCCodeFragment* vala_typeregister_function_real_get_type_interface_init_declaration (ValaTypeRegisterFunction* self);
static void vala_typeregister_function_real_get_type_interface_init_statements (ValaTypeRegisterFunction* self, ValaCCodeBlock* block, gboolean plugin);
ValaCCodeFragment* vala_typeregister_function_get_source_declaration (ValaTypeRegisterFunction* self);
ValaCCodeFragment* vala_typeregister_function_get_declaration (ValaTypeRegisterFunction* self);
ValaCCodeFragment* vala_typeregister_function_get_definition (ValaTypeRegisterFunction* self);
static ValaSymbolAccessibility vala_typeregister_function_real_get_accessibility (ValaTypeRegisterFunction* self);
ValaTypeRegisterFunction* vala_typeregister_function_construct (GType object_type);
void vala_typeregister_function_set_context (ValaTypeRegisterFunction* self, ValaCodeContext* value);
static void vala_typeregister_function_finalize (ValaTypeRegisterFunction* obj);


/**
 * Constructs the C function from the specified type.
 */
static gpointer _vala_ccode_node_ref0 (gpointer self) {
	return self ? vala_ccode_node_ref (self) : NULL;
}


void vala_typeregister_function_init_from_type (ValaTypeRegisterFunction* self, gboolean plugin, gboolean declaration_only) {
	gboolean use_thread_safe = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean fundamental = FALSE;
	ValaClass* cl = NULL;
	ValaTypeSymbol* _tmp1_ = NULL;
	ValaClass* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	ValaClass* _tmp5_ = NULL;
	gchar* type_id_name = NULL;
	ValaTypeSymbol* _tmp12_ = NULL;
	ValaTypeSymbol* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	ValaCCodeBlock* type_block = NULL;
	ValaCCodeBlock* _tmp18_ = NULL;
	ValaCCodeDeclaration* _cdecl_ = NULL;
	gboolean _tmp19_ = FALSE;
	ValaCCodeDeclaration* _tmp36_ = NULL;
	gboolean _tmp37_ = FALSE;
	gboolean _tmp42_ = FALSE;
	ValaCCodeFunction* fun = NULL;
	gboolean _tmp47_ = FALSE;
	gchar* type_value_table_decl_name = NULL;
	ValaCCodeBlock* type_init = NULL;
	ValaCCodeBlock* _tmp102_ = NULL;
	gboolean _tmp103_ = FALSE;
	ValaTypeSymbol* _tmp129_ = NULL;
	ValaTypeSymbol* _tmp130_ = NULL;
	gboolean _tmp131_ = FALSE;
	ValaCCodeBlock* _tmp170_ = NULL;
	ValaCCodeFragment* _tmp171_ = NULL;
	ValaCCodeFragment* _tmp172_ = NULL;
	gboolean _tmp173_ = FALSE;
	gboolean _tmp174_ = FALSE;
	ValaClass* _tmp175_ = NULL;
	ValaCCodeFunctionCall* reg_call = NULL;
	ValaTypeSymbol* _tmp211_ = NULL;
	ValaTypeSymbol* _tmp212_ = NULL;
	gboolean _tmp213_ = FALSE;
	ValaCCodeFunctionCall* _tmp260_ = NULL;
	ValaTypeSymbol* _tmp261_ = NULL;
	ValaTypeSymbol* _tmp262_ = NULL;
	gchar* _tmp263_ = NULL;
	gchar* _tmp264_ = NULL;
	gchar* _tmp265_ = NULL;
	gchar* _tmp266_ = NULL;
	ValaCCodeConstant* _tmp267_ = NULL;
	ValaCCodeConstant* _tmp268_ = NULL;
	ValaTypeSymbol* _tmp269_ = NULL;
	ValaTypeSymbol* _tmp270_ = NULL;
	gboolean _tmp271_ = FALSE;
	gboolean _tmp366_ = FALSE;
	gboolean _tmp367_ = FALSE;
	gboolean _tmp386_ = FALSE;
	gboolean _tmp387_ = FALSE;
	ValaClass* _tmp388_ = NULL;
	gboolean _tmp414_ = FALSE;
	gboolean _tmp417_ = FALSE;
	gboolean _tmp474_ = FALSE;
	ValaCCodeFunction* _tmp489_ = NULL;
	ValaCCodeFragment* _tmp490_ = NULL;
	ValaCCodeFunction* _tmp491_ = NULL;
	ValaCCodeFunction* _tmp492_ = NULL;
	ValaCCodeFunction* _tmp493_ = NULL;
	ValaCCodeFunction* _tmp494_ = NULL;
	ValaCCodeFunction* _tmp495_ = NULL;
	ValaCCodeBlock* _tmp496_ = NULL;
	ValaCCodeFragment* _tmp497_ = NULL;
	ValaCCodeFunction* _tmp498_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = plugin;
	use_thread_safe = !_tmp0_;
	fundamental = FALSE;
	_tmp1_ = vala_typeregister_function_get_type_declaration (self);
	_tmp2_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, VALA_TYPE_CLASS) ? ((ValaClass*) _tmp1_) : NULL;
	if (_tmp2_ == NULL) {
		_vala_code_node_unref0 (_tmp1_);
	}
	cl = _tmp2_;
	_tmp5_ = cl;
	if (_tmp5_ != NULL) {
		ValaClass* _tmp6_ = NULL;
		gboolean _tmp7_ = FALSE;
		gboolean _tmp8_ = FALSE;
		_tmp6_ = cl;
		_tmp7_ = vala_class_get_is_compact (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp4_ = !_tmp8_;
	} else {
		_tmp4_ = FALSE;
	}
	if (_tmp4_) {
		ValaClass* _tmp9_ = NULL;
		ValaClass* _tmp10_ = NULL;
		ValaClass* _tmp11_ = NULL;
		_tmp9_ = cl;
		_tmp10_ = vala_class_get_base_class (_tmp9_);
		_tmp11_ = _tmp10_;
		_tmp3_ = _tmp11_ == NULL;
	} else {
		_tmp3_ = FALSE;
	}
	if (_tmp3_) {
		fundamental = TRUE;
	}
	_tmp12_ = vala_typeregister_function_get_type_declaration (self);
	_tmp13_ = _tmp12_;
	_tmp14_ = vala_ccode_base_module_get_ccode_lower_case_name ((ValaCodeNode*) _tmp13_, NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = g_strdup_printf ("%s_type_id", _tmp15_);
	_tmp17_ = _tmp16_;
	_g_free0 (_tmp15_);
	_vala_code_node_unref0 (_tmp13_);
	type_id_name = _tmp17_;
	_tmp18_ = vala_ccode_block_new ();
	type_block = _tmp18_;
	_tmp19_ = use_thread_safe;
	if (_tmp19_) {
		ValaCCodeDeclaration* _tmp20_ = NULL;
		ValaCCodeDeclaration* _tmp21_ = NULL;
		const gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_ = NULL;
		ValaCCodeConstant* _tmp25_ = NULL;
		ValaCCodeConstant* _tmp26_ = NULL;
		ValaCCodeVariableDeclarator* _tmp27_ = NULL;
		ValaCCodeVariableDeclarator* _tmp28_ = NULL;
		_tmp20_ = vala_ccode_declaration_new ("gsize");
		_vala_ccode_node_unref0 (_cdecl_);
		_cdecl_ = _tmp20_;
		_tmp21_ = _cdecl_;
		_tmp22_ = type_id_name;
		_tmp23_ = g_strconcat (_tmp22_, "__volatile", NULL);
		_tmp24_ = _tmp23_;
		_tmp25_ = vala_ccode_constant_new ("0");
		_tmp26_ = _tmp25_;
		_tmp27_ = vala_ccode_variable_declarator_new (_tmp24_, (ValaCCodeExpression*) _tmp26_, NULL);
		_tmp28_ = _tmp27_;
		vala_ccode_declaration_add_declarator (_tmp21_, (ValaCCodeDeclarator*) _tmp28_);
		_vala_ccode_node_unref0 (_tmp28_);
		_vala_ccode_node_unref0 (_tmp26_);
		_g_free0 (_tmp24_);
	} else {
		ValaCCodeDeclaration* _tmp29_ = NULL;
		ValaCCodeDeclaration* _tmp30_ = NULL;
		const gchar* _tmp31_ = NULL;
		ValaCCodeConstant* _tmp32_ = NULL;
		ValaCCodeConstant* _tmp33_ = NULL;
		ValaCCodeVariableDeclarator* _tmp34_ = NULL;
		ValaCCodeVariableDeclarator* _tmp35_ = NULL;
		_tmp29_ = vala_ccode_declaration_new ("GType");
		_vala_ccode_node_unref0 (_cdecl_);
		_cdecl_ = _tmp29_;
		_tmp30_ = _cdecl_;
		_tmp31_ = type_id_name;
		_tmp32_ = vala_ccode_constant_new ("0");
		_tmp33_ = _tmp32_;
		_tmp34_ = vala_ccode_variable_declarator_new (_tmp31_, (ValaCCodeExpression*) _tmp33_, NULL);
		_tmp35_ = _tmp34_;
		vala_ccode_declaration_add_declarator (_tmp30_, (ValaCCodeDeclarator*) _tmp35_);
		_vala_ccode_node_unref0 (_tmp35_);
		_vala_ccode_node_unref0 (_tmp33_);
	}
	_tmp36_ = _cdecl_;
	vala_ccode_declaration_set_modifiers (_tmp36_, VALA_CCODE_MODIFIERS_STATIC);
	_tmp37_ = use_thread_safe;
	if (_tmp37_) {
		ValaCCodeDeclaration* _tmp38_ = NULL;
		ValaCCodeDeclaration* _tmp39_ = NULL;
		ValaCCodeModifiers _tmp40_ = 0;
		ValaCCodeModifiers _tmp41_ = 0;
		_tmp38_ = _cdecl_;
		_tmp39_ = _cdecl_;
		_tmp40_ = vala_ccode_declaration_get_modifiers (_tmp39_);
		_tmp41_ = _tmp40_;
		vala_ccode_declaration_set_modifiers (_tmp39_, _tmp41_ | VALA_CCODE_MODIFIERS_VOLATILE);
	}
	_tmp42_ = plugin;
	if (!_tmp42_) {
		ValaCCodeBlock* _tmp43_ = NULL;
		ValaCCodeDeclaration* _tmp44_ = NULL;
		_tmp43_ = type_block;
		_tmp44_ = _cdecl_;
		vala_ccode_block_add_statement (_tmp43_, (ValaCCodeNode*) _tmp44_);
	} else {
		ValaCCodeFragment* _tmp45_ = NULL;
		ValaCCodeDeclaration* _tmp46_ = NULL;
		_tmp45_ = self->priv->source_declaration_fragment;
		_tmp46_ = _cdecl_;
		vala_ccode_fragment_append (_tmp45_, (ValaCCodeNode*) _tmp46_);
	}
	_tmp47_ = plugin;
	if (!_tmp47_) {
		ValaTypeSymbol* _tmp48_ = NULL;
		ValaTypeSymbol* _tmp49_ = NULL;
		gchar* _tmp50_ = NULL;
		gchar* _tmp51_ = NULL;
		gchar* _tmp52_ = NULL;
		gchar* _tmp53_ = NULL;
		ValaCCodeFunction* _tmp54_ = NULL;
		ValaCCodeFunction* _tmp55_ = NULL;
		ValaSymbolAccessibility _tmp56_ = 0;
		_tmp48_ = vala_typeregister_function_get_type_declaration (self);
		_tmp49_ = _tmp48_;
		_tmp50_ = vala_ccode_base_module_get_ccode_lower_case_name ((ValaCodeNode*) _tmp49_, NULL);
		_tmp51_ = _tmp50_;
		_tmp52_ = g_strdup_printf ("%s_get_type", _tmp51_);
		_tmp53_ = _tmp52_;
		_tmp54_ = vala_ccode_function_new (_tmp53_, "GType");
		_vala_ccode_node_unref0 (fun);
		fun = _tmp54_;
		_g_free0 (_tmp53_);
		_g_free0 (_tmp51_);
		_vala_code_node_unref0 (_tmp49_);
		_tmp55_ = fun;
		vala_ccode_function_set_attributes (_tmp55_, "G_GNUC_CONST");
		_tmp56_ = vala_typeregister_function_get_accessibility (self);
		if (_tmp56_ == VALA_SYMBOL_ACCESSIBILITY_PRIVATE) {
			ValaCCodeFunction* _tmp57_ = NULL;
			ValaCCodeFunction* _tmp58_ = NULL;
			ValaCCodeFunction* _tmp59_ = NULL;
			const gchar* _tmp60_ = NULL;
			const gchar* _tmp61_ = NULL;
			gchar* _tmp62_ = NULL;
			gchar* _tmp63_ = NULL;
			_tmp57_ = fun;
			vala_ccode_function_set_modifiers (_tmp57_, VALA_CCODE_MODIFIERS_STATIC);
			_tmp58_ = fun;
			_tmp59_ = fun;
			_tmp60_ = vala_ccode_function_get_attributes (_tmp59_);
			_tmp61_ = _tmp60_;
			_tmp62_ = g_strconcat (_tmp61_, " G_GNUC_UNUSED", NULL);
			_tmp63_ = _tmp62_;
			vala_ccode_function_set_attributes (_tmp59_, _tmp63_);
			_g_free0 (_tmp63_);
		}
	} else {
		ValaTypeSymbol* _tmp64_ = NULL;
		ValaTypeSymbol* _tmp65_ = NULL;
		gchar* _tmp66_ = NULL;
		gchar* _tmp67_ = NULL;
		gchar* _tmp68_ = NULL;
		gchar* _tmp69_ = NULL;
		ValaCCodeFunction* _tmp70_ = NULL;
		ValaCCodeFunction* _tmp71_ = NULL;
		ValaCCodeParameter* _tmp72_ = NULL;
		ValaCCodeParameter* _tmp73_ = NULL;
		ValaCCodeFunction* get_fun = NULL;
		ValaTypeSymbol* _tmp74_ = NULL;
		ValaTypeSymbol* _tmp75_ = NULL;
		gchar* _tmp76_ = NULL;
		gchar* _tmp77_ = NULL;
		gchar* _tmp78_ = NULL;
		gchar* _tmp79_ = NULL;
		ValaCCodeFunction* _tmp80_ = NULL;
		ValaCCodeFunction* _tmp81_ = NULL;
		ValaCCodeFunction* _tmp82_ = NULL;
		ValaCCodeFunction* _tmp83_ = NULL;
		ValaCCodeFragment* _tmp84_ = NULL;
		ValaCCodeFunction* _tmp85_ = NULL;
		ValaCCodeFunction* _tmp86_ = NULL;
		ValaCCodeFunction* _tmp87_ = NULL;
		ValaCCodeFunction* _tmp88_ = NULL;
		ValaCCodeFunction* _tmp89_ = NULL;
		ValaCCodeBlock* _tmp90_ = NULL;
		ValaCCodeBlock* _tmp91_ = NULL;
		ValaCCodeFunction* _tmp92_ = NULL;
		ValaCCodeBlock* _tmp93_ = NULL;
		ValaCCodeBlock* _tmp94_ = NULL;
		const gchar* _tmp95_ = NULL;
		ValaCCodeIdentifier* _tmp96_ = NULL;
		ValaCCodeIdentifier* _tmp97_ = NULL;
		ValaCCodeReturnStatement* _tmp98_ = NULL;
		ValaCCodeReturnStatement* _tmp99_ = NULL;
		ValaCCodeFragment* _tmp100_ = NULL;
		ValaCCodeFunction* _tmp101_ = NULL;
		_tmp64_ = vala_typeregister_function_get_type_declaration (self);
		_tmp65_ = _tmp64_;
		_tmp66_ = vala_ccode_base_module_get_ccode_lower_case_name ((ValaCodeNode*) _tmp65_, NULL);
		_tmp67_ = _tmp66_;
		_tmp68_ = g_strdup_printf ("%s_register_type", _tmp67_);
		_tmp69_ = _tmp68_;
		_tmp70_ = vala_ccode_function_new (_tmp69_, "GType");
		_vala_ccode_node_unref0 (fun);
		fun = _tmp70_;
		_g_free0 (_tmp69_);
		_g_free0 (_tmp67_);
		_vala_code_node_unref0 (_tmp65_);
		_tmp71_ = fun;
		_tmp72_ = vala_ccode_parameter_new ("module", "GTypeModule *");
		_tmp73_ = _tmp72_;
		vala_ccode_function_add_parameter (_tmp71_, _tmp73_);
		_vala_ccode_node_unref0 (_tmp73_);
		_tmp74_ = vala_typeregister_function_get_type_declaration (self);
		_tmp75_ = _tmp74_;
		_tmp76_ = vala_ccode_base_module_get_ccode_lower_case_name ((ValaCodeNode*) _tmp75_, NULL);
		_tmp77_ = _tmp76_;
		_tmp78_ = g_strdup_printf ("%s_get_type", _tmp77_);
		_tmp79_ = _tmp78_;
		_tmp80_ = vala_ccode_function_new (_tmp79_, "GType");
		_tmp81_ = _tmp80_;
		_g_free0 (_tmp79_);
		_g_free0 (_tmp77_);
		_vala_code_node_unref0 (_tmp75_);
		get_fun = _tmp81_;
		_tmp82_ = get_fun;
		vala_ccode_function_set_attributes (_tmp82_, "G_GNUC_CONST");
		_tmp83_ = get_fun;
		vala_ccode_function_set_is_declaration (_tmp83_, TRUE);
		_tmp84_ = self->priv->declaration_fragment;
		_tmp85_ = get_fun;
		_tmp86_ = vala_ccode_function_copy (_tmp85_);
		_tmp87_ = _tmp86_;
		vala_ccode_fragment_append (_tmp84_, (ValaCCodeNode*) _tmp87_);
		_vala_ccode_node_unref0 (_tmp87_);
		_tmp88_ = get_fun;
		vala_ccode_function_set_is_declaration (_tmp88_, FALSE);
		_tmp89_ = get_fun;
		_tmp90_ = vala_ccode_block_new ();
		_tmp91_ = _tmp90_;
		vala_ccode_function_set_block (_tmp89_, _tmp91_);
		_vala_ccode_node_unref0 (_tmp91_);
		_tmp92_ = get_fun;
		_tmp93_ = vala_ccode_function_get_block (_tmp92_);
		_tmp94_ = _tmp93_;
		_tmp95_ = type_id_name;
		_tmp96_ = vala_ccode_identifier_new (_tmp95_);
		_tmp97_ = _tmp96_;
		_tmp98_ = vala_ccode_return_statement_new ((ValaCCodeExpression*) _tmp97_);
		_tmp99_ = _tmp98_;
		vala_ccode_block_add_statement (_tmp94_, (ValaCCodeNode*) _tmp99_);
		_vala_ccode_node_unref0 (_tmp99_);
		_vala_ccode_node_unref0 (_tmp97_);
		_tmp100_ = self->priv->definition_fragment;
		_tmp101_ = get_fun;
		vala_ccode_fragment_append (_tmp100_, (ValaCCodeNode*) _tmp101_);
		_vala_ccode_node_unref0 (get_fun);
	}
	type_value_table_decl_name = NULL;
	_tmp102_ = vala_ccode_block_new ();
	type_init = _tmp102_;
	_tmp103_ = fundamental;
	if (_tmp103_) {
		ValaCCodeDeclaration* cgtypetabledecl = NULL;
		ValaCCodeDeclaration* _tmp104_ = NULL;
		ValaCCodeDeclaration* _tmp105_ = NULL;
		ValaCCodeDeclaration* _tmp106_ = NULL;
		gchar* _tmp107_ = NULL;
		gchar* _tmp108_ = NULL;
		gchar* _tmp109_ = NULL;
		gchar* _tmp110_ = NULL;
		gchar* _tmp111_ = NULL;
		gchar* _tmp112_ = NULL;
		gchar* _tmp113_ = NULL;
		gchar* _tmp114_ = NULL;
		gchar* _tmp115_ = NULL;
		gchar* _tmp116_ = NULL;
		gchar* _tmp117_ = NULL;
		gchar* _tmp118_ = NULL;
		gchar* _tmp119_ = NULL;
		gchar* _tmp120_ = NULL;
		ValaCCodeConstant* _tmp121_ = NULL;
		ValaCCodeConstant* _tmp122_ = NULL;
		ValaCCodeVariableDeclarator* _tmp123_ = NULL;
		ValaCCodeVariableDeclarator* _tmp124_ = NULL;
		gchar* _tmp125_ = NULL;
		ValaCCodeBlock* _tmp126_ = NULL;
		ValaCCodeDeclaration* _tmp127_ = NULL;
		_tmp104_ = vala_ccode_declaration_new ("const GTypeValueTable");
		cgtypetabledecl = _tmp104_;
		_tmp105_ = cgtypetabledecl;
		vala_ccode_declaration_set_modifiers (_tmp105_, VALA_CCODE_MODIFIERS_STATIC);
		_tmp106_ = cgtypetabledecl;
		_tmp107_ = vala_typeregister_function_get_gtype_value_table_init_function_name (self);
		_tmp108_ = _tmp107_;
		_tmp109_ = vala_typeregister_function_get_gtype_value_table_free_function_name (self);
		_tmp110_ = _tmp109_;
		_tmp111_ = vala_typeregister_function_get_gtype_value_table_copy_function_name (self);
		_tmp112_ = _tmp111_;
		_tmp113_ = vala_typeregister_function_get_gtype_value_table_peek_pointer_function_name (self);
		_tmp114_ = _tmp113_;
		_tmp115_ = vala_typeregister_function_get_gtype_value_table_collect_value_function_name (self);
		_tmp116_ = _tmp115_;
		_tmp117_ = vala_typeregister_function_get_gtype_value_table_lcopy_value_function_name (self);
		_tmp118_ = _tmp117_;
		_tmp119_ = g_strdup_printf ("{ %s, %s, %s, %s, \"p\", %s, \"p\", %s }", _tmp108_, _tmp110_, _tmp112_, _tmp114_, _tmp116_, _tmp118_);
		_tmp120_ = _tmp119_;
		_tmp121_ = vala_ccode_constant_new (_tmp120_);
		_tmp122_ = _tmp121_;
		_tmp123_ = vala_ccode_variable_declarator_new ("g_define_type_value_table", (ValaCCodeExpression*) _tmp122_, NULL);
		_tmp124_ = _tmp123_;
		vala_ccode_declaration_add_declarator (_tmp106_, (ValaCCodeDeclarator*) _tmp124_);
		_vala_ccode_node_unref0 (_tmp124_);
		_vala_ccode_node_unref0 (_tmp122_);
		_g_free0 (_tmp120_);
		_g_free0 (_tmp118_);
		_g_free0 (_tmp116_);
		_g_free0 (_tmp114_);
		_g_free0 (_tmp112_);
		_g_free0 (_tmp110_);
		_g_free0 (_tmp108_);
		_tmp125_ = g_strdup ("&g_define_type_value_table");
		_g_free0 (type_value_table_decl_name);
		type_value_table_decl_name = _tmp125_;
		_tmp126_ = type_init;
		_tmp127_ = cgtypetabledecl;
		vala_ccode_block_add_statement (_tmp126_, (ValaCCodeNode*) _tmp127_);
		_vala_ccode_node_unref0 (cgtypetabledecl);
	} else {
		gchar* _tmp128_ = NULL;
		_tmp128_ = g_strdup ("NULL");
		_g_free0 (type_value_table_decl_name);
		type_value_table_decl_name = _tmp128_;
	}
	_tmp129_ = vala_typeregister_function_get_type_declaration (self);
	_tmp130_ = _tmp129_;
	_tmp131_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp130_, VALA_TYPE_OBJECT_TYPE_SYMBOL);
	_vala_code_node_unref0 (_tmp130_);
	if (_tmp131_) {
		ValaCCodeDeclaration* ctypedecl = NULL;
		ValaCCodeDeclaration* _tmp132_ = NULL;
		ValaCCodeDeclaration* _tmp133_ = NULL;
		gchar* _tmp134_ = NULL;
		gboolean _tmp135_ = FALSE;
		ValaCCodeDeclaration* _tmp138_ = NULL;
		gchar* _tmp139_ = NULL;
		gchar* _tmp140_ = NULL;
		gchar* _tmp141_ = NULL;
		gchar* _tmp142_ = NULL;
		gchar* _tmp143_ = NULL;
		gchar* _tmp144_ = NULL;
		gchar* _tmp145_ = NULL;
		gchar* _tmp146_ = NULL;
		gchar* _tmp147_ = NULL;
		gchar* _tmp148_ = NULL;
		gchar* _tmp149_ = NULL;
		gchar* _tmp150_ = NULL;
		const gchar* _tmp151_ = NULL;
		gchar* _tmp152_ = NULL;
		gchar* _tmp153_ = NULL;
		ValaCCodeConstant* _tmp154_ = NULL;
		ValaCCodeConstant* _tmp155_ = NULL;
		ValaCCodeVariableDeclarator* _tmp156_ = NULL;
		ValaCCodeVariableDeclarator* _tmp157_ = NULL;
		ValaCCodeBlock* _tmp158_ = NULL;
		ValaCCodeDeclaration* _tmp159_ = NULL;
		gboolean _tmp160_ = FALSE;
		_tmp132_ = vala_ccode_declaration_new ("const GTypeInfo");
		ctypedecl = _tmp132_;
		_tmp133_ = ctypedecl;
		vala_ccode_declaration_set_modifiers (_tmp133_, VALA_CCODE_MODIFIERS_STATIC);
		_tmp135_ = plugin;
		if (_tmp135_) {
			gchar* _tmp136_ = NULL;
			_tmp136_ = vala_typeregister_function_get_base_finalize_func_name (self);
			_g_free0 (_tmp134_);
			_tmp134_ = _tmp136_;
		} else {
			gchar* _tmp137_ = NULL;
			_tmp137_ = g_strdup ("NULL");
			_g_free0 (_tmp134_);
			_tmp134_ = _tmp137_;
		}
		_tmp138_ = ctypedecl;
		_tmp139_ = vala_typeregister_function_get_type_struct_name (self);
		_tmp140_ = _tmp139_;
		_tmp141_ = vala_typeregister_function_get_base_init_func_name (self);
		_tmp142_ = _tmp141_;
		_tmp143_ = vala_typeregister_function_get_class_init_func_name (self);
		_tmp144_ = _tmp143_;
		_tmp145_ = vala_typeregister_function_get_class_finalize_func_name (self);
		_tmp146_ = _tmp145_;
		_tmp147_ = vala_typeregister_function_get_instance_struct_size (self);
		_tmp148_ = _tmp147_;
		_tmp149_ = vala_typeregister_function_get_instance_init_func_name (self);
		_tmp150_ = _tmp149_;
		_tmp151_ = type_value_table_decl_name;
		_tmp152_ = g_strdup_printf ("{ sizeof (%s), (GBaseInitFunc) %s, (GBaseFinalizeFunc) %s, (GClassInit" \
"Func) %s, (GClassFinalizeFunc) %s, NULL, %s, 0, (GInstanceInitFunc) %s" \
", %s }", _tmp140_, _tmp142_, _tmp134_, _tmp144_, _tmp146_, _tmp148_, _tmp150_, _tmp151_);
		_tmp153_ = _tmp152_;
		_tmp154_ = vala_ccode_constant_new (_tmp153_);
		_tmp155_ = _tmp154_;
		_tmp156_ = vala_ccode_variable_declarator_new ("g_define_type_info", (ValaCCodeExpression*) _tmp155_, NULL);
		_tmp157_ = _tmp156_;
		vala_ccode_declaration_add_declarator (_tmp138_, (ValaCCodeDeclarator*) _tmp157_);
		_vala_ccode_node_unref0 (_tmp157_);
		_vala_ccode_node_unref0 (_tmp155_);
		_g_free0 (_tmp153_);
		_g_free0 (_tmp150_);
		_g_free0 (_tmp148_);
		_g_free0 (_tmp146_);
		_g_free0 (_tmp144_);
		_g_free0 (_tmp142_);
		_g_free0 (_tmp140_);
		_tmp158_ = type_init;
		_tmp159_ = ctypedecl;
		vala_ccode_block_add_statement (_tmp158_, (ValaCCodeNode*) _tmp159_);
		_tmp160_ = fundamental;
		if (_tmp160_) {
			ValaCCodeDeclaration* ctypefundamentaldecl = NULL;
			ValaCCodeDeclaration* _tmp161_ = NULL;
			ValaCCodeDeclaration* _tmp162_ = NULL;
			ValaCCodeDeclaration* _tmp163_ = NULL;
			ValaCCodeConstant* _tmp164_ = NULL;
			ValaCCodeConstant* _tmp165_ = NULL;
			ValaCCodeVariableDeclarator* _tmp166_ = NULL;
			ValaCCodeVariableDeclarator* _tmp167_ = NULL;
			ValaCCodeBlock* _tmp168_ = NULL;
			ValaCCodeDeclaration* _tmp169_ = NULL;
			_tmp161_ = vala_ccode_declaration_new ("const GTypeFundamentalInfo");
			ctypefundamentaldecl = _tmp161_;
			_tmp162_ = ctypefundamentaldecl;
			vala_ccode_declaration_set_modifiers (_tmp162_, VALA_CCODE_MODIFIERS_STATIC);
			_tmp163_ = ctypefundamentaldecl;
			_tmp164_ = vala_ccode_constant_new ("{ (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERI" \
"VABLE | G_TYPE_FLAG_DEEP_DERIVABLE) }");
			_tmp165_ = _tmp164_;
			_tmp166_ = vala_ccode_variable_declarator_new ("g_define_type_fundamental_info", (ValaCCodeExpression*) _tmp165_, NULL);
			_tmp167_ = _tmp166_;
			vala_ccode_declaration_add_declarator (_tmp163_, (ValaCCodeDeclarator*) _tmp167_);
			_vala_ccode_node_unref0 (_tmp167_);
			_vala_ccode_node_unref0 (_tmp165_);
			_tmp168_ = type_init;
			_tmp169_ = ctypefundamentaldecl;
			vala_ccode_block_add_statement (_tmp168_, (ValaCCodeNode*) _tmp169_);
			_vala_ccode_node_unref0 (ctypefundamentaldecl);
		}
		_g_free0 (_tmp134_);
		_vala_ccode_node_unref0 (ctypedecl);
	}
	_tmp170_ = type_init;
	_tmp171_ = vala_typeregister_function_get_type_interface_init_declaration (self);
	_tmp172_ = _tmp171_;
	vala_ccode_block_add_statement (_tmp170_, (ValaCCodeNode*) _tmp172_);
	_vala_ccode_node_unref0 (_tmp172_);
	_tmp175_ = cl;
	if (_tmp175_ != NULL) {
		ValaClass* _tmp176_ = NULL;
		gboolean _tmp177_ = FALSE;
		gboolean _tmp178_ = FALSE;
		_tmp176_ = cl;
		_tmp177_ = vala_class_get_has_class_private_fields (_tmp176_);
		_tmp178_ = _tmp177_;
		_tmp174_ = _tmp178_;
	} else {
		_tmp174_ = FALSE;
	}
	if (_tmp174_) {
		ValaCodeContext* _tmp179_ = NULL;
		gboolean _tmp180_ = FALSE;
		_tmp179_ = self->priv->_context;
		_tmp180_ = vala_code_context_require_glib_version (_tmp179_, 2, 24);
		_tmp173_ = !_tmp180_;
	} else {
		_tmp173_ = FALSE;
	}
	if (_tmp173_) {
		ValaCCodeFunctionCall* quark_reg_call = NULL;
		gboolean _tmp181_ = FALSE;
		ValaCCodeFunctionCall* _tmp188_ = NULL;
		ValaTypeSymbol* _tmp189_ = NULL;
		ValaTypeSymbol* _tmp190_ = NULL;
		gchar* _tmp191_ = NULL;
		gchar* _tmp192_ = NULL;
		gchar* _tmp193_ = NULL;
		gchar* _tmp194_ = NULL;
		ValaCCodeConstant* _tmp195_ = NULL;
		ValaCCodeConstant* _tmp196_ = NULL;
		ValaCCodeBlock* _tmp197_ = NULL;
		ValaTypeSymbol* _tmp198_ = NULL;
		ValaTypeSymbol* _tmp199_ = NULL;
		gchar* _tmp200_ = NULL;
		gchar* _tmp201_ = NULL;
		gchar* _tmp202_ = NULL;
		gchar* _tmp203_ = NULL;
		ValaCCodeIdentifier* _tmp204_ = NULL;
		ValaCCodeIdentifier* _tmp205_ = NULL;
		ValaCCodeFunctionCall* _tmp206_ = NULL;
		ValaCCodeAssignment* _tmp207_ = NULL;
		ValaCCodeAssignment* _tmp208_ = NULL;
		ValaCCodeExpressionStatement* _tmp209_ = NULL;
		ValaCCodeExpressionStatement* _tmp210_ = NULL;
		_tmp181_ = plugin;
		if (_tmp181_) {
			ValaCCodeIdentifier* _tmp182_ = NULL;
			ValaCCodeIdentifier* _tmp183_ = NULL;
			ValaCCodeFunctionCall* _tmp184_ = NULL;
			_tmp182_ = vala_ccode_identifier_new ("g_quark_from_string");
			_tmp183_ = _tmp182_;
			_tmp184_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp183_);
			_vala_ccode_node_unref0 (quark_reg_call);
			quark_reg_call = _tmp184_;
			_vala_ccode_node_unref0 (_tmp183_);
		} else {
			ValaCCodeIdentifier* _tmp185_ = NULL;
			ValaCCodeIdentifier* _tmp186_ = NULL;
			ValaCCodeFunctionCall* _tmp187_ = NULL;
			_tmp185_ = vala_ccode_identifier_new ("g_quark_from_static_string");
			_tmp186_ = _tmp185_;
			_tmp187_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp186_);
			_vala_ccode_node_unref0 (quark_reg_call);
			quark_reg_call = _tmp187_;
			_vala_ccode_node_unref0 (_tmp186_);
		}
		_tmp188_ = quark_reg_call;
		_tmp189_ = vala_typeregister_function_get_type_declaration (self);
		_tmp190_ = _tmp189_;
		_tmp191_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp190_);
		_tmp192_ = _tmp191_;
		_tmp193_ = g_strdup_printf ("\"Vala%sClassPrivate\"", _tmp192_);
		_tmp194_ = _tmp193_;
		_tmp195_ = vala_ccode_constant_new (_tmp194_);
		_tmp196_ = _tmp195_;
		vala_ccode_function_call_add_argument (_tmp188_, (ValaCCodeExpression*) _tmp196_);
		_vala_ccode_node_unref0 (_tmp196_);
		_g_free0 (_tmp194_);
		_g_free0 (_tmp192_);
		_vala_code_node_unref0 (_tmp190_);
		_tmp197_ = type_init;
		_tmp198_ = vala_typeregister_function_get_type_declaration (self);
		_tmp199_ = _tmp198_;
		_tmp200_ = vala_ccode_base_module_get_ccode_lower_case_name ((ValaCodeNode*) _tmp199_, NULL);
		_tmp201_ = _tmp200_;
		_tmp202_ = g_strdup_printf ("_vala_%s_class_private_quark", _tmp201_);
		_tmp203_ = _tmp202_;
		_tmp204_ = vala_ccode_identifier_new (_tmp203_);
		_tmp205_ = _tmp204_;
		_tmp206_ = quark_reg_call;
		_tmp207_ = vala_ccode_assignment_new ((ValaCCodeExpression*) _tmp205_, (ValaCCodeExpression*) _tmp206_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
		_tmp208_ = _tmp207_;
		_tmp209_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) _tmp208_);
		_tmp210_ = _tmp209_;
		vala_ccode_block_add_statement (_tmp197_, (ValaCCodeNode*) _tmp210_);
		_vala_ccode_node_unref0 (_tmp210_);
		_vala_ccode_node_unref0 (_tmp208_);
		_vala_ccode_node_unref0 (_tmp205_);
		_g_free0 (_tmp203_);
		_g_free0 (_tmp201_);
		_vala_code_node_unref0 (_tmp199_);
		_vala_ccode_node_unref0 (quark_reg_call);
	}
	_tmp211_ = vala_typeregister_function_get_type_declaration (self);
	_tmp212_ = _tmp211_;
	_tmp213_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp212_, VALA_TYPE_STRUCT);
	_vala_code_node_unref0 (_tmp212_);
	if (_tmp213_) {
		ValaCCodeIdentifier* _tmp214_ = NULL;
		ValaCCodeIdentifier* _tmp215_ = NULL;
		ValaCCodeFunctionCall* _tmp216_ = NULL;
		_tmp214_ = vala_ccode_identifier_new ("g_boxed_type_register_static");
		_tmp215_ = _tmp214_;
		_tmp216_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp215_);
		_vala_ccode_node_unref0 (reg_call);
		reg_call = _tmp216_;
		_vala_ccode_node_unref0 (_tmp215_);
	} else {
		ValaTypeSymbol* _tmp217_ = NULL;
		ValaTypeSymbol* _tmp218_ = NULL;
		gboolean _tmp219_ = FALSE;
		_tmp217_ = vala_typeregister_function_get_type_declaration (self);
		_tmp218_ = _tmp217_;
		_tmp219_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp218_, VALA_TYPE_ENUM);
		_vala_code_node_unref0 (_tmp218_);
		if (_tmp219_) {
			ValaEnum* en = NULL;
			ValaTypeSymbol* _tmp220_ = NULL;
			ValaEnum* _tmp221_ = NULL;
			ValaEnum* _tmp222_ = NULL;
			gboolean _tmp223_ = FALSE;
			gboolean _tmp224_ = FALSE;
			_tmp220_ = vala_typeregister_function_get_type_declaration (self);
			_tmp221_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp220_, VALA_TYPE_ENUM) ? ((ValaEnum*) _tmp220_) : NULL;
			if (_tmp221_ == NULL) {
				_vala_code_node_unref0 (_tmp220_);
			}
			en = _tmp221_;
			_tmp222_ = en;
			_tmp223_ = vala_enum_get_is_flags (_tmp222_);
			_tmp224_ = _tmp223_;
			if (_tmp224_) {
				ValaCCodeIdentifier* _tmp225_ = NULL;
				ValaCCodeIdentifier* _tmp226_ = NULL;
				ValaCCodeFunctionCall* _tmp227_ = NULL;
				_tmp225_ = vala_ccode_identifier_new ("g_flags_register_static");
				_tmp226_ = _tmp225_;
				_tmp227_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp226_);
				_vala_ccode_node_unref0 (reg_call);
				reg_call = _tmp227_;
				_vala_ccode_node_unref0 (_tmp226_);
			} else {
				ValaCCodeIdentifier* _tmp228_ = NULL;
				ValaCCodeIdentifier* _tmp229_ = NULL;
				ValaCCodeFunctionCall* _tmp230_ = NULL;
				_tmp228_ = vala_ccode_identifier_new ("g_enum_register_static");
				_tmp229_ = _tmp228_;
				_tmp230_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp229_);
				_vala_ccode_node_unref0 (reg_call);
				reg_call = _tmp230_;
				_vala_ccode_node_unref0 (_tmp229_);
			}
			_vala_code_node_unref0 (en);
		} else {
			gboolean _tmp231_ = FALSE;
			_tmp231_ = fundamental;
			if (_tmp231_) {
				ValaCCodeIdentifier* _tmp232_ = NULL;
				ValaCCodeIdentifier* _tmp233_ = NULL;
				ValaCCodeFunctionCall* _tmp234_ = NULL;
				ValaCCodeFunctionCall* _tmp235_ = NULL;
				ValaCCodeIdentifier* _tmp236_ = NULL;
				ValaCCodeIdentifier* _tmp237_ = NULL;
				ValaCCodeFunctionCall* _tmp238_ = NULL;
				ValaCCodeFunctionCall* _tmp239_ = NULL;
				_tmp232_ = vala_ccode_identifier_new ("g_type_register_fundamental");
				_tmp233_ = _tmp232_;
				_tmp234_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp233_);
				_vala_ccode_node_unref0 (reg_call);
				reg_call = _tmp234_;
				_vala_ccode_node_unref0 (_tmp233_);
				_tmp235_ = reg_call;
				_tmp236_ = vala_ccode_identifier_new ("g_type_fundamental_next");
				_tmp237_ = _tmp236_;
				_tmp238_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp237_);
				_tmp239_ = _tmp238_;
				vala_ccode_function_call_add_argument (_tmp235_, (ValaCCodeExpression*) _tmp239_);
				_vala_ccode_node_unref0 (_tmp239_);
				_vala_ccode_node_unref0 (_tmp237_);
			} else {
				gboolean _tmp240_ = FALSE;
				_tmp240_ = plugin;
				if (!_tmp240_) {
					ValaCCodeIdentifier* _tmp241_ = NULL;
					ValaCCodeIdentifier* _tmp242_ = NULL;
					ValaCCodeFunctionCall* _tmp243_ = NULL;
					ValaCCodeFunctionCall* _tmp244_ = NULL;
					gchar* _tmp245_ = NULL;
					gchar* _tmp246_ = NULL;
					ValaCCodeIdentifier* _tmp247_ = NULL;
					ValaCCodeIdentifier* _tmp248_ = NULL;
					_tmp241_ = vala_ccode_identifier_new ("g_type_register_static");
					_tmp242_ = _tmp241_;
					_tmp243_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp242_);
					_vala_ccode_node_unref0 (reg_call);
					reg_call = _tmp243_;
					_vala_ccode_node_unref0 (_tmp242_);
					_tmp244_ = reg_call;
					_tmp245_ = vala_typeregister_function_get_parent_type_name (self);
					_tmp246_ = _tmp245_;
					_tmp247_ = vala_ccode_identifier_new (_tmp246_);
					_tmp248_ = _tmp247_;
					vala_ccode_function_call_add_argument (_tmp244_, (ValaCCodeExpression*) _tmp248_);
					_vala_ccode_node_unref0 (_tmp248_);
					_g_free0 (_tmp246_);
				} else {
					ValaCCodeIdentifier* _tmp249_ = NULL;
					ValaCCodeIdentifier* _tmp250_ = NULL;
					ValaCCodeFunctionCall* _tmp251_ = NULL;
					ValaCCodeFunctionCall* _tmp252_ = NULL;
					ValaCCodeIdentifier* _tmp253_ = NULL;
					ValaCCodeIdentifier* _tmp254_ = NULL;
					ValaCCodeFunctionCall* _tmp255_ = NULL;
					gchar* _tmp256_ = NULL;
					gchar* _tmp257_ = NULL;
					ValaCCodeIdentifier* _tmp258_ = NULL;
					ValaCCodeIdentifier* _tmp259_ = NULL;
					_tmp249_ = vala_ccode_identifier_new ("g_type_module_register_type");
					_tmp250_ = _tmp249_;
					_tmp251_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp250_);
					_vala_ccode_node_unref0 (reg_call);
					reg_call = _tmp251_;
					_vala_ccode_node_unref0 (_tmp250_);
					_tmp252_ = reg_call;
					_tmp253_ = vala_ccode_identifier_new ("module");
					_tmp254_ = _tmp253_;
					vala_ccode_function_call_add_argument (_tmp252_, (ValaCCodeExpression*) _tmp254_);
					_vala_ccode_node_unref0 (_tmp254_);
					_tmp255_ = reg_call;
					_tmp256_ = vala_typeregister_function_get_parent_type_name (self);
					_tmp257_ = _tmp256_;
					_tmp258_ = vala_ccode_identifier_new (_tmp257_);
					_tmp259_ = _tmp258_;
					vala_ccode_function_call_add_argument (_tmp255_, (ValaCCodeExpression*) _tmp259_);
					_vala_ccode_node_unref0 (_tmp259_);
					_g_free0 (_tmp257_);
				}
			}
		}
	}
	_tmp260_ = reg_call;
	_tmp261_ = vala_typeregister_function_get_type_declaration (self);
	_tmp262_ = _tmp261_;
	_tmp263_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp262_);
	_tmp264_ = _tmp263_;
	_tmp265_ = g_strdup_printf ("\"%s\"", _tmp264_);
	_tmp266_ = _tmp265_;
	_tmp267_ = vala_ccode_constant_new (_tmp266_);
	_tmp268_ = _tmp267_;
	vala_ccode_function_call_add_argument (_tmp260_, (ValaCCodeExpression*) _tmp268_);
	_vala_ccode_node_unref0 (_tmp268_);
	_g_free0 (_tmp266_);
	_g_free0 (_tmp264_);
	_vala_code_node_unref0 (_tmp262_);
	_tmp269_ = vala_typeregister_function_get_type_declaration (self);
	_tmp270_ = _tmp269_;
	_tmp271_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp270_, VALA_TYPE_STRUCT);
	_vala_code_node_unref0 (_tmp270_);
	if (_tmp271_) {
		ValaStruct* st = NULL;
		ValaTypeSymbol* _tmp272_ = NULL;
		ValaCCodeFunctionCall* _tmp273_ = NULL;
		ValaStruct* _tmp274_ = NULL;
		gchar* _tmp275_ = NULL;
		gchar* _tmp276_ = NULL;
		ValaCCodeIdentifier* _tmp277_ = NULL;
		ValaCCodeIdentifier* _tmp278_ = NULL;
		ValaCCodeCastExpression* _tmp279_ = NULL;
		ValaCCodeCastExpression* _tmp280_ = NULL;
		ValaCCodeFunctionCall* _tmp281_ = NULL;
		ValaStruct* _tmp282_ = NULL;
		gchar* _tmp283_ = NULL;
		gchar* _tmp284_ = NULL;
		ValaCCodeIdentifier* _tmp285_ = NULL;
		ValaCCodeIdentifier* _tmp286_ = NULL;
		ValaCCodeCastExpression* _tmp287_ = NULL;
		ValaCCodeCastExpression* _tmp288_ = NULL;
		_tmp272_ = vala_typeregister_function_get_type_declaration (self);
		st = G_TYPE_CHECK_INSTANCE_CAST (_tmp272_, VALA_TYPE_STRUCT, ValaStruct);
		_tmp273_ = reg_call;
		_tmp274_ = st;
		_tmp275_ = vala_ccode_base_module_get_ccode_dup_function ((ValaTypeSymbol*) _tmp274_);
		_tmp276_ = _tmp275_;
		_tmp277_ = vala_ccode_identifier_new (_tmp276_);
		_tmp278_ = _tmp277_;
		_tmp279_ = vala_ccode_cast_expression_new ((ValaCCodeExpression*) _tmp278_, "GBoxedCopyFunc");
		_tmp280_ = _tmp279_;
		vala_ccode_function_call_add_argument (_tmp273_, (ValaCCodeExpression*) _tmp280_);
		_vala_ccode_node_unref0 (_tmp280_);
		_vala_ccode_node_unref0 (_tmp278_);
		_g_free0 (_tmp276_);
		_tmp281_ = reg_call;
		_tmp282_ = st;
		_tmp283_ = vala_ccode_base_module_get_ccode_free_function ((ValaTypeSymbol*) _tmp282_);
		_tmp284_ = _tmp283_;
		_tmp285_ = vala_ccode_identifier_new (_tmp284_);
		_tmp286_ = _tmp285_;
		_tmp287_ = vala_ccode_cast_expression_new ((ValaCCodeExpression*) _tmp286_, "GBoxedFreeFunc");
		_tmp288_ = _tmp287_;
		vala_ccode_function_call_add_argument (_tmp281_, (ValaCCodeExpression*) _tmp288_);
		_vala_ccode_node_unref0 (_tmp288_);
		_vala_ccode_node_unref0 (_tmp286_);
		_g_free0 (_tmp284_);
		_vala_code_node_unref0 (st);
	} else {
		ValaTypeSymbol* _tmp289_ = NULL;
		ValaTypeSymbol* _tmp290_ = NULL;
		gboolean _tmp291_ = FALSE;
		_tmp289_ = vala_typeregister_function_get_type_declaration (self);
		_tmp290_ = _tmp289_;
		_tmp291_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp290_, VALA_TYPE_ENUM);
		_vala_code_node_unref0 (_tmp290_);
		if (_tmp291_) {
			ValaEnum* en = NULL;
			ValaTypeSymbol* _tmp292_ = NULL;
			ValaEnum* _tmp293_ = NULL;
			ValaCCodeInitializerList* clist = NULL;
			ValaCCodeInitializerList* _tmp294_ = NULL;
			ValaCCodeInitializerList* clist_ev = NULL;
			ValaCCodeInitializerList* _tmp327_ = NULL;
			ValaCCodeInitializerList* _tmp328_ = NULL;
			ValaCCodeConstant* _tmp329_ = NULL;
			ValaCCodeConstant* _tmp330_ = NULL;
			ValaCCodeInitializerList* _tmp331_ = NULL;
			ValaCCodeConstant* _tmp332_ = NULL;
			ValaCCodeConstant* _tmp333_ = NULL;
			ValaCCodeInitializerList* _tmp334_ = NULL;
			ValaCCodeConstant* _tmp335_ = NULL;
			ValaCCodeConstant* _tmp336_ = NULL;
			ValaCCodeInitializerList* _tmp337_ = NULL;
			ValaCCodeInitializerList* _tmp338_ = NULL;
			ValaCCodeVariableDeclarator* enum_decl = NULL;
			ValaCCodeInitializerList* _tmp339_ = NULL;
			ValaCCodeVariableDeclarator* _tmp340_ = NULL;
			ValaEnum* _tmp341_ = NULL;
			gboolean _tmp342_ = FALSE;
			gboolean _tmp343_ = FALSE;
			ValaCCodeDeclaration* _tmp346_ = NULL;
			ValaCCodeVariableDeclarator* _tmp347_ = NULL;
			ValaCCodeDeclaration* _tmp348_ = NULL;
			ValaCCodeBlock* _tmp349_ = NULL;
			ValaCCodeDeclaration* _tmp350_ = NULL;
			ValaCCodeFunctionCall* _tmp351_ = NULL;
			ValaCCodeIdentifier* _tmp352_ = NULL;
			ValaCCodeIdentifier* _tmp353_ = NULL;
			_tmp292_ = vala_typeregister_function_get_type_declaration (self);
			_tmp293_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp292_, VALA_TYPE_ENUM) ? ((ValaEnum*) _tmp292_) : NULL;
			if (_tmp293_ == NULL) {
				_vala_code_node_unref0 (_tmp292_);
			}
			en = _tmp293_;
			_tmp294_ = vala_ccode_initializer_list_new ();
			clist = _tmp294_;
			clist_ev = NULL;
			{
				ValaList* _ev_list = NULL;
				ValaEnum* _tmp295_ = NULL;
				ValaList* _tmp296_ = NULL;
				gint _ev_size = 0;
				ValaList* _tmp297_ = NULL;
				gint _tmp298_ = 0;
				gint _tmp299_ = 0;
				gint _ev_index = 0;
				_tmp295_ = en;
				_tmp296_ = vala_enum_get_values (_tmp295_);
				_ev_list = _tmp296_;
				_tmp297_ = _ev_list;
				_tmp298_ = vala_collection_get_size ((ValaCollection*) _tmp297_);
				_tmp299_ = _tmp298_;
				_ev_size = _tmp299_;
				_ev_index = -1;
				while (TRUE) {
					gint _tmp300_ = 0;
					gint _tmp301_ = 0;
					gint _tmp302_ = 0;
					ValaEnumValue* ev = NULL;
					ValaList* _tmp303_ = NULL;
					gint _tmp304_ = 0;
					gpointer _tmp305_ = NULL;
					ValaCCodeInitializerList* _tmp306_ = NULL;
					ValaCCodeInitializerList* _tmp307_ = NULL;
					ValaEnumValue* _tmp308_ = NULL;
					gchar* _tmp309_ = NULL;
					gchar* _tmp310_ = NULL;
					ValaCCodeConstant* _tmp311_ = NULL;
					ValaCCodeConstant* _tmp312_ = NULL;
					ValaCCodeInitializerList* _tmp313_ = NULL;
					ValaEnumValue* _tmp314_ = NULL;
					gchar* _tmp315_ = NULL;
					gchar* _tmp316_ = NULL;
					gchar* _tmp317_ = NULL;
					gchar* _tmp318_ = NULL;
					ValaCCodeIdentifier* _tmp319_ = NULL;
					ValaCCodeIdentifier* _tmp320_ = NULL;
					ValaCCodeInitializerList* _tmp321_ = NULL;
					ValaEnumValue* _tmp322_ = NULL;
					ValaCCodeConstant* _tmp323_ = NULL;
					ValaCCodeConstant* _tmp324_ = NULL;
					ValaCCodeInitializerList* _tmp325_ = NULL;
					ValaCCodeInitializerList* _tmp326_ = NULL;
					_tmp300_ = _ev_index;
					_ev_index = _tmp300_ + 1;
					_tmp301_ = _ev_index;
					_tmp302_ = _ev_size;
					if (!(_tmp301_ < _tmp302_)) {
						break;
					}
					_tmp303_ = _ev_list;
					_tmp304_ = _ev_index;
					_tmp305_ = vala_list_get (_tmp303_, _tmp304_);
					ev = (ValaEnumValue*) _tmp305_;
					_tmp306_ = vala_ccode_initializer_list_new ();
					_vala_ccode_node_unref0 (clist_ev);
					clist_ev = _tmp306_;
					_tmp307_ = clist_ev;
					_tmp308_ = ev;
					_tmp309_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp308_);
					_tmp310_ = _tmp309_;
					_tmp311_ = vala_ccode_constant_new (_tmp310_);
					_tmp312_ = _tmp311_;
					vala_ccode_initializer_list_append (_tmp307_, (ValaCCodeExpression*) _tmp312_);
					_vala_ccode_node_unref0 (_tmp312_);
					_g_free0 (_tmp310_);
					_tmp313_ = clist_ev;
					_tmp314_ = ev;
					_tmp315_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp314_);
					_tmp316_ = _tmp315_;
					_tmp317_ = g_strdup_printf ("\"%s\"", _tmp316_);
					_tmp318_ = _tmp317_;
					_tmp319_ = vala_ccode_identifier_new (_tmp318_);
					_tmp320_ = _tmp319_;
					vala_ccode_initializer_list_append (_tmp313_, (ValaCCodeExpression*) _tmp320_);
					_vala_ccode_node_unref0 (_tmp320_);
					_g_free0 (_tmp318_);
					_g_free0 (_tmp316_);
					_tmp321_ = clist_ev;
					_tmp322_ = ev;
					_tmp323_ = vala_ccode_base_module_get_enum_value_canonical_cconstant (_tmp322_);
					_tmp324_ = _tmp323_;
					vala_ccode_initializer_list_append (_tmp321_, (ValaCCodeExpression*) _tmp324_);
					_vala_ccode_node_unref0 (_tmp324_);
					_tmp325_ = clist;
					_tmp326_ = clist_ev;
					vala_ccode_initializer_list_append (_tmp325_, (ValaCCodeExpression*) _tmp326_);
					_vala_code_node_unref0 (ev);
				}
				_vala_iterable_unref0 (_ev_list);
			}
			_tmp327_ = vala_ccode_initializer_list_new ();
			_vala_ccode_node_unref0 (clist_ev);
			clist_ev = _tmp327_;
			_tmp328_ = clist_ev;
			_tmp329_ = vala_ccode_constant_new ("0");
			_tmp330_ = _tmp329_;
			vala_ccode_initializer_list_append (_tmp328_, (ValaCCodeExpression*) _tmp330_);
			_vala_ccode_node_unref0 (_tmp330_);
			_tmp331_ = clist_ev;
			_tmp332_ = vala_ccode_constant_new ("NULL");
			_tmp333_ = _tmp332_;
			vala_ccode_initializer_list_append (_tmp331_, (ValaCCodeExpression*) _tmp333_);
			_vala_ccode_node_unref0 (_tmp333_);
			_tmp334_ = clist_ev;
			_tmp335_ = vala_ccode_constant_new ("NULL");
			_tmp336_ = _tmp335_;
			vala_ccode_initializer_list_append (_tmp334_, (ValaCCodeExpression*) _tmp336_);
			_vala_ccode_node_unref0 (_tmp336_);
			_tmp337_ = clist;
			_tmp338_ = clist_ev;
			vala_ccode_initializer_list_append (_tmp337_, (ValaCCodeExpression*) _tmp338_);
			_tmp339_ = clist;
			_tmp340_ = vala_ccode_variable_declarator_new ("values[]", (ValaCCodeExpression*) _tmp339_, NULL);
			enum_decl = _tmp340_;
			_tmp341_ = en;
			_tmp342_ = vala_enum_get_is_flags (_tmp341_);
			_tmp343_ = _tmp342_;
			if (_tmp343_) {
				ValaCCodeDeclaration* _tmp344_ = NULL;
				_tmp344_ = vala_ccode_declaration_new ("const GFlagsValue");
				_vala_ccode_node_unref0 (_cdecl_);
				_cdecl_ = _tmp344_;
			} else {
				ValaCCodeDeclaration* _tmp345_ = NULL;
				_tmp345_ = vala_ccode_declaration_new ("const GEnumValue");
				_vala_ccode_node_unref0 (_cdecl_);
				_cdecl_ = _tmp345_;
			}
			_tmp346_ = _cdecl_;
			_tmp347_ = enum_decl;
			vala_ccode_declaration_add_declarator (_tmp346_, (ValaCCodeDeclarator*) _tmp347_);
			_tmp348_ = _cdecl_;
			vala_ccode_declaration_set_modifiers (_tmp348_, VALA_CCODE_MODIFIERS_STATIC);
			_tmp349_ = type_init;
			_tmp350_ = _cdecl_;
			vala_ccode_block_add_statement (_tmp349_, (ValaCCodeNode*) _tmp350_);
			_tmp351_ = reg_call;
			_tmp352_ = vala_ccode_identifier_new ("values");
			_tmp353_ = _tmp352_;
			vala_ccode_function_call_add_argument (_tmp351_, (ValaCCodeExpression*) _tmp353_);
			_vala_ccode_node_unref0 (_tmp353_);
			_vala_ccode_node_unref0 (enum_decl);
			_vala_ccode_node_unref0 (clist_ev);
			_vala_ccode_node_unref0 (clist);
			_vala_code_node_unref0 (en);
		} else {
			ValaCCodeFunctionCall* _tmp354_ = NULL;
			ValaCCodeIdentifier* _tmp355_ = NULL;
			ValaCCodeIdentifier* _tmp356_ = NULL;
			gboolean _tmp357_ = FALSE;
			ValaCCodeFunctionCall* _tmp361_ = NULL;
			gchar* _tmp362_ = NULL;
			gchar* _tmp363_ = NULL;
			ValaCCodeConstant* _tmp364_ = NULL;
			ValaCCodeConstant* _tmp365_ = NULL;
			_tmp354_ = reg_call;
			_tmp355_ = vala_ccode_identifier_new ("&g_define_type_info");
			_tmp356_ = _tmp355_;
			vala_ccode_function_call_add_argument (_tmp354_, (ValaCCodeExpression*) _tmp356_);
			_vala_ccode_node_unref0 (_tmp356_);
			_tmp357_ = fundamental;
			if (_tmp357_) {
				ValaCCodeFunctionCall* _tmp358_ = NULL;
				ValaCCodeIdentifier* _tmp359_ = NULL;
				ValaCCodeIdentifier* _tmp360_ = NULL;
				_tmp358_ = reg_call;
				_tmp359_ = vala_ccode_identifier_new ("&g_define_type_fundamental_info");
				_tmp360_ = _tmp359_;
				vala_ccode_function_call_add_argument (_tmp358_, (ValaCCodeExpression*) _tmp360_);
				_vala_ccode_node_unref0 (_tmp360_);
			}
			_tmp361_ = reg_call;
			_tmp362_ = vala_typeregister_function_get_type_flags (self);
			_tmp363_ = _tmp362_;
			_tmp364_ = vala_ccode_constant_new (_tmp363_);
			_tmp365_ = _tmp364_;
			vala_ccode_function_call_add_argument (_tmp361_, (ValaCCodeExpression*) _tmp365_);
			_vala_ccode_node_unref0 (_tmp365_);
			_g_free0 (_tmp363_);
		}
	}
	_tmp367_ = use_thread_safe;
	if (_tmp367_) {
		gboolean _tmp368_ = FALSE;
		_tmp368_ = plugin;
		_tmp366_ = !_tmp368_;
	} else {
		_tmp366_ = FALSE;
	}
	if (_tmp366_) {
		ValaCCodeDeclaration* temp_decl = NULL;
		ValaCCodeDeclaration* _tmp369_ = NULL;
		ValaCCodeDeclaration* _tmp370_ = NULL;
		const gchar* _tmp371_ = NULL;
		ValaCCodeFunctionCall* _tmp372_ = NULL;
		ValaCCodeVariableDeclarator* _tmp373_ = NULL;
		ValaCCodeVariableDeclarator* _tmp374_ = NULL;
		ValaCCodeBlock* _tmp375_ = NULL;
		ValaCCodeDeclaration* _tmp376_ = NULL;
		_tmp369_ = vala_ccode_declaration_new ("GType");
		temp_decl = _tmp369_;
		_tmp370_ = temp_decl;
		_tmp371_ = type_id_name;
		_tmp372_ = reg_call;
		_tmp373_ = vala_ccode_variable_declarator_new (_tmp371_, (ValaCCodeExpression*) _tmp372_, NULL);
		_tmp374_ = _tmp373_;
		vala_ccode_declaration_add_declarator (_tmp370_, (ValaCCodeDeclarator*) _tmp374_);
		_vala_ccode_node_unref0 (_tmp374_);
		_tmp375_ = type_init;
		_tmp376_ = temp_decl;
		vala_ccode_block_add_statement (_tmp375_, (ValaCCodeNode*) _tmp376_);
		_vala_ccode_node_unref0 (temp_decl);
	} else {
		ValaCCodeBlock* _tmp377_ = NULL;
		const gchar* _tmp378_ = NULL;
		ValaCCodeIdentifier* _tmp379_ = NULL;
		ValaCCodeIdentifier* _tmp380_ = NULL;
		ValaCCodeFunctionCall* _tmp381_ = NULL;
		ValaCCodeAssignment* _tmp382_ = NULL;
		ValaCCodeAssignment* _tmp383_ = NULL;
		ValaCCodeExpressionStatement* _tmp384_ = NULL;
		ValaCCodeExpressionStatement* _tmp385_ = NULL;
		_tmp377_ = type_init;
		_tmp378_ = type_id_name;
		_tmp379_ = vala_ccode_identifier_new (_tmp378_);
		_tmp380_ = _tmp379_;
		_tmp381_ = reg_call;
		_tmp382_ = vala_ccode_assignment_new ((ValaCCodeExpression*) _tmp380_, (ValaCCodeExpression*) _tmp381_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
		_tmp383_ = _tmp382_;
		_tmp384_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) _tmp383_);
		_tmp385_ = _tmp384_;
		vala_ccode_block_add_statement (_tmp377_, (ValaCCodeNode*) _tmp385_);
		_vala_ccode_node_unref0 (_tmp385_);
		_vala_ccode_node_unref0 (_tmp383_);
		_vala_ccode_node_unref0 (_tmp380_);
	}
	_tmp388_ = cl;
	if (_tmp388_ != NULL) {
		ValaClass* _tmp389_ = NULL;
		gboolean _tmp390_ = FALSE;
		gboolean _tmp391_ = FALSE;
		_tmp389_ = cl;
		_tmp390_ = vala_class_get_has_class_private_fields (_tmp389_);
		_tmp391_ = _tmp390_;
		_tmp387_ = _tmp391_;
	} else {
		_tmp387_ = FALSE;
	}
	if (_tmp387_) {
		ValaCodeContext* _tmp392_ = NULL;
		gboolean _tmp393_ = FALSE;
		_tmp392_ = self->priv->_context;
		_tmp393_ = vala_code_context_require_glib_version (_tmp392_, 2, 24);
		_tmp386_ = _tmp393_;
	} else {
		_tmp386_ = FALSE;
	}
	if (_tmp386_) {
		ValaCCodeFunctionCall* add_class_private_call = NULL;
		ValaCCodeIdentifier* _tmp394_ = NULL;
		ValaCCodeIdentifier* _tmp395_ = NULL;
		ValaCCodeFunctionCall* _tmp396_ = NULL;
		ValaCCodeFunctionCall* _tmp397_ = NULL;
		const gchar* _tmp398_ = NULL;
		ValaCCodeIdentifier* _tmp399_ = NULL;
		ValaCCodeIdentifier* _tmp400_ = NULL;
		ValaCCodeFunctionCall* _tmp401_ = NULL;
		ValaTypeSymbol* _tmp402_ = NULL;
		ValaTypeSymbol* _tmp403_ = NULL;
		gchar* _tmp404_ = NULL;
		gchar* _tmp405_ = NULL;
		gchar* _tmp406_ = NULL;
		gchar* _tmp407_ = NULL;
		ValaCCodeIdentifier* _tmp408_ = NULL;
		ValaCCodeIdentifier* _tmp409_ = NULL;
		ValaCCodeBlock* _tmp410_ = NULL;
		ValaCCodeFunctionCall* _tmp411_ = NULL;
		ValaCCodeExpressionStatement* _tmp412_ = NULL;
		ValaCCodeExpressionStatement* _tmp413_ = NULL;
		_tmp394_ = vala_ccode_identifier_new ("g_type_add_class_private");
		_tmp395_ = _tmp394_;
		_tmp396_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp395_);
		_vala_ccode_node_unref0 (add_class_private_call);
		add_class_private_call = _tmp396_;
		_vala_ccode_node_unref0 (_tmp395_);
		_tmp397_ = add_class_private_call;
		_tmp398_ = type_id_name;
		_tmp399_ = vala_ccode_identifier_new (_tmp398_);
		_tmp400_ = _tmp399_;
		vala_ccode_function_call_add_argument (_tmp397_, (ValaCCodeExpression*) _tmp400_);
		_vala_ccode_node_unref0 (_tmp400_);
		_tmp401_ = add_class_private_call;
		_tmp402_ = vala_typeregister_function_get_type_declaration (self);
		_tmp403_ = _tmp402_;
		_tmp404_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp403_);
		_tmp405_ = _tmp404_;
		_tmp406_ = g_strdup_printf ("sizeof (%sClassPrivate)", _tmp405_);
		_tmp407_ = _tmp406_;
		_tmp408_ = vala_ccode_identifier_new (_tmp407_);
		_tmp409_ = _tmp408_;
		vala_ccode_function_call_add_argument (_tmp401_, (ValaCCodeExpression*) _tmp409_);
		_vala_ccode_node_unref0 (_tmp409_);
		_g_free0 (_tmp407_);
		_g_free0 (_tmp405_);
		_vala_code_node_unref0 (_tmp403_);
		_tmp410_ = type_init;
		_tmp411_ = add_class_private_call;
		_tmp412_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) _tmp411_);
		_tmp413_ = _tmp412_;
		vala_ccode_block_add_statement (_tmp410_, (ValaCCodeNode*) _tmp413_);
		_vala_ccode_node_unref0 (_tmp413_);
		_vala_ccode_node_unref0 (add_class_private_call);
	}
	_tmp414_ = declaration_only;
	if (!_tmp414_) {
		ValaCCodeBlock* _tmp415_ = NULL;
		gboolean _tmp416_ = FALSE;
		_tmp415_ = type_init;
		_tmp416_ = plugin;
		vala_typeregister_function_get_type_interface_init_statements (self, _tmp415_, _tmp416_);
	}
	_tmp417_ = plugin;
	if (!_tmp417_) {
		ValaCCodeExpression* condition = NULL;
		gboolean _tmp418_ = FALSE;
		ValaCCodeExpression* cond = NULL;
		gboolean _tmp459_ = FALSE;
		ValaCCodeIfStatement* cif = NULL;
		ValaCCodeExpression* _tmp467_ = NULL;
		ValaCCodeBlock* _tmp468_ = NULL;
		ValaCCodeIfStatement* _tmp469_ = NULL;
		ValaCCodeBlock* _tmp470_ = NULL;
		ValaCCodeIfStatement* _tmp471_ = NULL;
		_tmp418_ = use_thread_safe;
		if (_tmp418_) {
			ValaCCodeFunctionCall* enter = NULL;
			ValaCCodeIdentifier* _tmp419_ = NULL;
			ValaCCodeIdentifier* _tmp420_ = NULL;
			ValaCCodeFunctionCall* _tmp421_ = NULL;
			ValaCCodeFunctionCall* _tmp422_ = NULL;
			ValaCCodeFunctionCall* _tmp423_ = NULL;
			const gchar* _tmp424_ = NULL;
			gchar* _tmp425_ = NULL;
			gchar* _tmp426_ = NULL;
			ValaCCodeIdentifier* _tmp427_ = NULL;
			ValaCCodeIdentifier* _tmp428_ = NULL;
			ValaCCodeUnaryExpression* _tmp429_ = NULL;
			ValaCCodeUnaryExpression* _tmp430_ = NULL;
			ValaCCodeFunctionCall* _tmp431_ = NULL;
			ValaCCodeExpression* _tmp432_ = NULL;
			ValaCCodeFunctionCall* leave = NULL;
			ValaCCodeIdentifier* _tmp433_ = NULL;
			ValaCCodeIdentifier* _tmp434_ = NULL;
			ValaCCodeFunctionCall* _tmp435_ = NULL;
			ValaCCodeFunctionCall* _tmp436_ = NULL;
			ValaCCodeFunctionCall* _tmp437_ = NULL;
			const gchar* _tmp438_ = NULL;
			gchar* _tmp439_ = NULL;
			gchar* _tmp440_ = NULL;
			ValaCCodeIdentifier* _tmp441_ = NULL;
			ValaCCodeIdentifier* _tmp442_ = NULL;
			ValaCCodeUnaryExpression* _tmp443_ = NULL;
			ValaCCodeUnaryExpression* _tmp444_ = NULL;
			ValaCCodeFunctionCall* _tmp445_ = NULL;
			const gchar* _tmp446_ = NULL;
			ValaCCodeIdentifier* _tmp447_ = NULL;
			ValaCCodeIdentifier* _tmp448_ = NULL;
			ValaCCodeBlock* _tmp449_ = NULL;
			ValaCCodeFunctionCall* _tmp450_ = NULL;
			ValaCCodeExpressionStatement* _tmp451_ = NULL;
			ValaCCodeExpressionStatement* _tmp452_ = NULL;
			_tmp419_ = vala_ccode_identifier_new ("g_once_init_enter");
			_tmp420_ = _tmp419_;
			_tmp421_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp420_);
			_tmp422_ = _tmp421_;
			_vala_ccode_node_unref0 (_tmp420_);
			enter = _tmp422_;
			_tmp423_ = enter;
			_tmp424_ = type_id_name;
			_tmp425_ = g_strconcat (_tmp424_, "__volatile", NULL);
			_tmp426_ = _tmp425_;
			_tmp427_ = vala_ccode_identifier_new (_tmp426_);
			_tmp428_ = _tmp427_;
			_tmp429_ = vala_ccode_unary_expression_new (VALA_CCODE_UNARY_OPERATOR_ADDRESS_OF, (ValaCCodeExpression*) _tmp428_);
			_tmp430_ = _tmp429_;
			vala_ccode_function_call_add_argument (_tmp423_, (ValaCCodeExpression*) _tmp430_);
			_vala_ccode_node_unref0 (_tmp430_);
			_vala_ccode_node_unref0 (_tmp428_);
			_g_free0 (_tmp426_);
			_tmp431_ = enter;
			_tmp432_ = _vala_ccode_node_ref0 ((ValaCCodeExpression*) _tmp431_);
			_vala_ccode_node_unref0 (condition);
			condition = _tmp432_;
			_tmp433_ = vala_ccode_identifier_new ("g_once_init_leave");
			_tmp434_ = _tmp433_;
			_tmp435_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp434_);
			_tmp436_ = _tmp435_;
			_vala_ccode_node_unref0 (_tmp434_);
			leave = _tmp436_;
			_tmp437_ = leave;
			_tmp438_ = type_id_name;
			_tmp439_ = g_strconcat (_tmp438_, "__volatile", NULL);
			_tmp440_ = _tmp439_;
			_tmp441_ = vala_ccode_identifier_new (_tmp440_);
			_tmp442_ = _tmp441_;
			_tmp443_ = vala_ccode_unary_expression_new (VALA_CCODE_UNARY_OPERATOR_ADDRESS_OF, (ValaCCodeExpression*) _tmp442_);
			_tmp444_ = _tmp443_;
			vala_ccode_function_call_add_argument (_tmp437_, (ValaCCodeExpression*) _tmp444_);
			_vala_ccode_node_unref0 (_tmp444_);
			_vala_ccode_node_unref0 (_tmp442_);
			_g_free0 (_tmp440_);
			_tmp445_ = leave;
			_tmp446_ = type_id_name;
			_tmp447_ = vala_ccode_identifier_new (_tmp446_);
			_tmp448_ = _tmp447_;
			vala_ccode_function_call_add_argument (_tmp445_, (ValaCCodeExpression*) _tmp448_);
			_vala_ccode_node_unref0 (_tmp448_);
			_tmp449_ = type_init;
			_tmp450_ = leave;
			_tmp451_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) _tmp450_);
			_tmp452_ = _tmp451_;
			vala_ccode_block_add_statement (_tmp449_, (ValaCCodeNode*) _tmp452_);
			_vala_ccode_node_unref0 (_tmp452_);
			_vala_ccode_node_unref0 (leave);
			_vala_ccode_node_unref0 (enter);
		} else {
			ValaCCodeIdentifier* id = NULL;
			const gchar* _tmp453_ = NULL;
			ValaCCodeIdentifier* _tmp454_ = NULL;
			ValaCCodeConstant* zero = NULL;
			ValaCCodeConstant* _tmp455_ = NULL;
			ValaCCodeIdentifier* _tmp456_ = NULL;
			ValaCCodeConstant* _tmp457_ = NULL;
			ValaCCodeBinaryExpression* _tmp458_ = NULL;
			_tmp453_ = type_id_name;
			_tmp454_ = vala_ccode_identifier_new (_tmp453_);
			id = _tmp454_;
			_tmp455_ = vala_ccode_constant_new ("0");
			zero = _tmp455_;
			_tmp456_ = id;
			_tmp457_ = zero;
			_tmp458_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_EQUALITY, (ValaCCodeExpression*) _tmp456_, (ValaCCodeExpression*) _tmp457_);
			_vala_ccode_node_unref0 (condition);
			condition = (ValaCCodeExpression*) _tmp458_;
			_vala_ccode_node_unref0 (zero);
			_vala_ccode_node_unref0 (id);
		}
		_tmp459_ = use_thread_safe;
		if (_tmp459_) {
			ValaCCodeExpression* _tmp460_ = NULL;
			ValaCCodeExpression* _tmp461_ = NULL;
			_tmp460_ = condition;
			_tmp461_ = _vala_ccode_node_ref0 (_tmp460_);
			_vala_ccode_node_unref0 (cond);
			cond = _tmp461_;
		} else {
			ValaCCodeIdentifier* _tmp462_ = NULL;
			ValaCCodeIdentifier* _tmp463_ = NULL;
			ValaCCodeFunctionCall* _tmp464_ = NULL;
			ValaCCodeExpression* _tmp465_ = NULL;
			ValaCCodeExpression* _tmp466_ = NULL;
			_tmp462_ = vala_ccode_identifier_new ("G_UNLIKELY");
			_tmp463_ = _tmp462_;
			_tmp464_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp463_);
			_vala_ccode_node_unref0 (cond);
			cond = (ValaCCodeExpression*) _tmp464_;
			_vala_ccode_node_unref0 (_tmp463_);
			_tmp465_ = cond;
			_tmp466_ = condition;
			vala_ccode_function_call_add_argument (G_TYPE_CHECK_INSTANCE_TYPE (_tmp465_, VALA_TYPE_CCODE_FUNCTION_CALL) ? ((ValaCCodeFunctionCall*) _tmp465_) : NULL, _tmp466_);
		}
		_tmp467_ = cond;
		_tmp468_ = type_init;
		_tmp469_ = vala_ccode_if_statement_new (_tmp467_, (ValaCCodeStatement*) _tmp468_, NULL);
		cif = _tmp469_;
		_tmp470_ = type_block;
		_tmp471_ = cif;
		vala_ccode_block_add_statement (_tmp470_, (ValaCCodeNode*) _tmp471_);
		_vala_ccode_node_unref0 (cif);
		_vala_ccode_node_unref0 (cond);
		_vala_ccode_node_unref0 (condition);
	} else {
		ValaCCodeBlock* _tmp472_ = NULL;
		ValaCCodeBlock* _tmp473_ = NULL;
		_tmp472_ = type_init;
		_tmp473_ = _vala_ccode_node_ref0 (_tmp472_);
		_vala_ccode_node_unref0 (type_block);
		type_block = _tmp473_;
	}
	_tmp474_ = use_thread_safe;
	if (_tmp474_) {
		ValaCCodeBlock* _tmp475_ = NULL;
		const gchar* _tmp476_ = NULL;
		gchar* _tmp477_ = NULL;
		gchar* _tmp478_ = NULL;
		ValaCCodeIdentifier* _tmp479_ = NULL;
		ValaCCodeIdentifier* _tmp480_ = NULL;
		ValaCCodeReturnStatement* _tmp481_ = NULL;
		ValaCCodeReturnStatement* _tmp482_ = NULL;
		_tmp475_ = type_block;
		_tmp476_ = type_id_name;
		_tmp477_ = g_strconcat (_tmp476_, "__volatile", NULL);
		_tmp478_ = _tmp477_;
		_tmp479_ = vala_ccode_identifier_new (_tmp478_);
		_tmp480_ = _tmp479_;
		_tmp481_ = vala_ccode_return_statement_new ((ValaCCodeExpression*) _tmp480_);
		_tmp482_ = _tmp481_;
		vala_ccode_block_add_statement (_tmp475_, (ValaCCodeNode*) _tmp482_);
		_vala_ccode_node_unref0 (_tmp482_);
		_vala_ccode_node_unref0 (_tmp480_);
		_g_free0 (_tmp478_);
	} else {
		ValaCCodeBlock* _tmp483_ = NULL;
		const gchar* _tmp484_ = NULL;
		ValaCCodeIdentifier* _tmp485_ = NULL;
		ValaCCodeIdentifier* _tmp486_ = NULL;
		ValaCCodeReturnStatement* _tmp487_ = NULL;
		ValaCCodeReturnStatement* _tmp488_ = NULL;
		_tmp483_ = type_block;
		_tmp484_ = type_id_name;
		_tmp485_ = vala_ccode_identifier_new (_tmp484_);
		_tmp486_ = _tmp485_;
		_tmp487_ = vala_ccode_return_statement_new ((ValaCCodeExpression*) _tmp486_);
		_tmp488_ = _tmp487_;
		vala_ccode_block_add_statement (_tmp483_, (ValaCCodeNode*) _tmp488_);
		_vala_ccode_node_unref0 (_tmp488_);
		_vala_ccode_node_unref0 (_tmp486_);
	}
	_tmp489_ = fun;
	vala_ccode_function_set_is_declaration (_tmp489_, TRUE);
	_tmp490_ = self->priv->declaration_fragment;
	_tmp491_ = fun;
	_tmp492_ = vala_ccode_function_copy (_tmp491_);
	_tmp493_ = _tmp492_;
	vala_ccode_fragment_append (_tmp490_, (ValaCCodeNode*) _tmp493_);
	_vala_ccode_node_unref0 (_tmp493_);
	_tmp494_ = fun;
	vala_ccode_function_set_is_declaration (_tmp494_, FALSE);
	_tmp495_ = fun;
	_tmp496_ = type_block;
	vala_ccode_function_set_block (_tmp495_, _tmp496_);
	_tmp497_ = self->priv->definition_fragment;
	_tmp498_ = fun;
	vala_ccode_fragment_append (_tmp497_, (ValaCCodeNode*) _tmp498_);
	_vala_ccode_node_unref0 (reg_call);
	_vala_ccode_node_unref0 (type_init);
	_g_free0 (type_value_table_decl_name);
	_vala_ccode_node_unref0 (fun);
	_vala_ccode_node_unref0 (_cdecl_);
	_vala_ccode_node_unref0 (type_block);
	_g_free0 (type_id_name);
	_vala_code_node_unref0 (cl);
}


/**
 * Returns the data type to be registered.
 *
 * @return type to be registered
 */
static ValaTypeSymbol* vala_typeregister_function_real_get_type_declaration (ValaTypeRegisterFunction* self) {
	g_critical ("Type `%s' does not implement abstract method `vala_typeregister_function_get_type_declaration'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return NULL;
}


ValaTypeSymbol* vala_typeregister_function_get_type_declaration (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_type_declaration (self);
}


/**
 * Returns the name of the type struct in C code.
 *
 * @return C struct name
 */
static gchar* vala_typeregister_function_real_get_type_struct_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar* vala_typeregister_function_get_type_struct_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_type_struct_name (self);
}


/**
 * Returns the name of the base_init function in C code.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_base_init_func_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar* vala_typeregister_function_get_base_init_func_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_base_init_func_name (self);
}


/**
 * Returns the name of the class_finalize function in C code.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_class_finalize_func_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar* vala_typeregister_function_get_class_finalize_func_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_class_finalize_func_name (self);
}


/**
 * Returns the name of the base_finalize function in C code.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_base_finalize_func_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar* vala_typeregister_function_get_base_finalize_func_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_base_finalize_func_name (self);
}


/**
 * Returns the name of the class_init function in C code.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_class_init_func_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar* vala_typeregister_function_get_class_init_func_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_class_init_func_name (self);
}


/**
 * Returns the size of the instance struct in C code.
 *
 * @return C instance struct size
 */
static gchar* vala_typeregister_function_real_get_instance_struct_size (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar* vala_typeregister_function_get_instance_struct_size (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_instance_struct_size (self);
}


/**
 * Returns the name of the instance_init function in C code.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_instance_init_func_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar* vala_typeregister_function_get_instance_init_func_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_instance_init_func_name (self);
}


/**
 * Returns the name of the parent type in C code.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_parent_type_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	g_assert_not_reached ();
	return result;
}


gchar* vala_typeregister_function_get_parent_type_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_parent_type_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable init function or null when not available.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_gtype_value_table_init_function_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar* vala_typeregister_function_get_gtype_value_table_init_function_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_init_function_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable peek pointer function or null when not available.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_gtype_value_table_peek_pointer_function_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar* vala_typeregister_function_get_gtype_value_table_peek_pointer_function_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_peek_pointer_function_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable free function or null when not available.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_gtype_value_table_free_function_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar* vala_typeregister_function_get_gtype_value_table_free_function_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_free_function_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable copy function or null when not available.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_gtype_value_table_copy_function_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar* vala_typeregister_function_get_gtype_value_table_copy_function_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_copy_function_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable lcopy function or null when not available.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_gtype_value_table_lcopy_value_function_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar* vala_typeregister_function_get_gtype_value_table_lcopy_value_function_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_lcopy_value_function_name (self);
}


/**
 * Returns the C-name of the new generated GTypeValueTable collect value function or null when not available.
 *
 * @return C function name
 */
static gchar* vala_typeregister_function_real_get_gtype_value_table_collect_value_function_name (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	result = NULL;
	return result;
}


gchar* vala_typeregister_function_get_gtype_value_table_collect_value_function_name (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_gtype_value_table_collect_value_function_name (self);
}


/**
 * Returns the set of type flags to be applied when registering.
 *
 * @return type flags
 */
static gchar* vala_typeregister_function_real_get_type_flags (ValaTypeRegisterFunction* self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	_tmp0_ = g_strdup ("0");
	result = _tmp0_;
	return result;
}


gchar* vala_typeregister_function_get_type_flags (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_type_flags (self);
}


/**
 * Returns additional C declarations to setup interfaces.
 *
 * @return C declarations
 */
static ValaCCodeFragment* vala_typeregister_function_real_get_type_interface_init_declaration (ValaTypeRegisterFunction* self) {
	ValaCCodeFragment* result = NULL;
	ValaCCodeFragment* _tmp0_ = NULL;
	_tmp0_ = vala_ccode_fragment_new ();
	result = _tmp0_;
	return result;
}


ValaCCodeFragment* vala_typeregister_function_get_type_interface_init_declaration (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_type_interface_init_declaration (self);
}


/**
 * Returns additional C initialization statements to setup interfaces.
 *
 * @return C statements
 */
static void vala_typeregister_function_real_get_type_interface_init_statements (ValaTypeRegisterFunction* self, ValaCCodeBlock* block, gboolean plugin) {
	g_return_if_fail (block != NULL);
}


void vala_typeregister_function_get_type_interface_init_statements (ValaTypeRegisterFunction* self, ValaCCodeBlock* block, gboolean plugin) {
	g_return_if_fail (self != NULL);
	VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_type_interface_init_statements (self, block, plugin);
}


ValaCCodeFragment* vala_typeregister_function_get_source_declaration (ValaTypeRegisterFunction* self) {
	ValaCCodeFragment* result = NULL;
	ValaCCodeFragment* _tmp0_ = NULL;
	ValaCCodeFragment* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->source_declaration_fragment;
	_tmp1_ = _vala_ccode_node_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


/**
 * Returns the declaration for this type register function in C code.
 *
 * @return C function declaration fragment
 */
ValaCCodeFragment* vala_typeregister_function_get_declaration (ValaTypeRegisterFunction* self) {
	ValaCCodeFragment* result = NULL;
	ValaCCodeFragment* _tmp0_ = NULL;
	ValaCCodeFragment* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->declaration_fragment;
	_tmp1_ = _vala_ccode_node_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


/**
 * Returns the definition for this type register function in C code.
 *
 * @return C function definition fragment
 */
ValaCCodeFragment* vala_typeregister_function_get_definition (ValaTypeRegisterFunction* self) {
	ValaCCodeFragment* result = NULL;
	ValaCCodeFragment* _tmp0_ = NULL;
	ValaCCodeFragment* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->definition_fragment;
	_tmp1_ = _vala_ccode_node_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


/**
 * Returns the accessibility for this type.
 */
static ValaSymbolAccessibility vala_typeregister_function_real_get_accessibility (ValaTypeRegisterFunction* self) {
	g_critical ("Type `%s' does not implement abstract method `vala_typeregister_function_get_accessibility'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return 0;
}


ValaSymbolAccessibility vala_typeregister_function_get_accessibility (ValaTypeRegisterFunction* self) {
	g_return_val_if_fail (self != NULL, 0);
	return VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->get_accessibility (self);
}


ValaTypeRegisterFunction* vala_typeregister_function_construct (GType object_type) {
	ValaTypeRegisterFunction* self = NULL;
	self = (ValaTypeRegisterFunction*) g_type_create_instance (object_type);
	return self;
}


ValaCodeContext* vala_typeregister_function_get_context (ValaTypeRegisterFunction* self) {
	ValaCodeContext* result;
	ValaCodeContext* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_context;
	result = _tmp0_;
	return result;
}


static gpointer _vala_code_context_ref0 (gpointer self) {
	return self ? vala_code_context_ref (self) : NULL;
}


void vala_typeregister_function_set_context (ValaTypeRegisterFunction* self, ValaCodeContext* value) {
	ValaCodeContext* _tmp0_ = NULL;
	ValaCodeContext* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _vala_code_context_ref0 (_tmp0_);
	_vala_code_context_unref0 (self->priv->_context);
	self->priv->_context = _tmp1_;
}


static void vala_value_typeregister_function_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void vala_value_typeregister_function_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		vala_typeregister_function_unref (value->data[0].v_pointer);
	}
}


static void vala_value_typeregister_function_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = vala_typeregister_function_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer vala_value_typeregister_function_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* vala_value_typeregister_function_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ValaTypeRegisterFunction* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = vala_typeregister_function_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* vala_value_typeregister_function_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ValaTypeRegisterFunction** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = vala_typeregister_function_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* vala_param_spec_typeregister_function (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ValaParamSpecTypeRegisterFunction* spec;
	g_return_val_if_fail (g_type_is_a (object_type, VALA_TYPE_TYPEREGISTER_FUNCTION), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer vala_value_get_typeregister_function (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALA_TYPE_TYPEREGISTER_FUNCTION), NULL);
	return value->data[0].v_pointer;
}


void vala_value_set_typeregister_function (GValue* value, gpointer v_object) {
	ValaTypeRegisterFunction* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALA_TYPE_TYPEREGISTER_FUNCTION));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, VALA_TYPE_TYPEREGISTER_FUNCTION));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		vala_typeregister_function_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		vala_typeregister_function_unref (old);
	}
}


void vala_value_take_typeregister_function (GValue* value, gpointer v_object) {
	ValaTypeRegisterFunction* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALA_TYPE_TYPEREGISTER_FUNCTION));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, VALA_TYPE_TYPEREGISTER_FUNCTION));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		vala_typeregister_function_unref (old);
	}
}


static void vala_typeregister_function_class_init (ValaTypeRegisterFunctionClass * klass) {
	vala_typeregister_function_parent_class = g_type_class_peek_parent (klass);
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->finalize = vala_typeregister_function_finalize;
	g_type_class_add_private (klass, sizeof (ValaTypeRegisterFunctionPrivate));
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_type_declaration = vala_typeregister_function_real_get_type_declaration;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_type_struct_name = vala_typeregister_function_real_get_type_struct_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_base_init_func_name = vala_typeregister_function_real_get_base_init_func_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_class_finalize_func_name = vala_typeregister_function_real_get_class_finalize_func_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_base_finalize_func_name = vala_typeregister_function_real_get_base_finalize_func_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_class_init_func_name = vala_typeregister_function_real_get_class_init_func_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_instance_struct_size = vala_typeregister_function_real_get_instance_struct_size;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_instance_init_func_name = vala_typeregister_function_real_get_instance_init_func_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_parent_type_name = vala_typeregister_function_real_get_parent_type_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_gtype_value_table_init_function_name = vala_typeregister_function_real_get_gtype_value_table_init_function_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_gtype_value_table_peek_pointer_function_name = vala_typeregister_function_real_get_gtype_value_table_peek_pointer_function_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_gtype_value_table_free_function_name = vala_typeregister_function_real_get_gtype_value_table_free_function_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_gtype_value_table_copy_function_name = vala_typeregister_function_real_get_gtype_value_table_copy_function_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_gtype_value_table_lcopy_value_function_name = vala_typeregister_function_real_get_gtype_value_table_lcopy_value_function_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_gtype_value_table_collect_value_function_name = vala_typeregister_function_real_get_gtype_value_table_collect_value_function_name;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_type_flags = vala_typeregister_function_real_get_type_flags;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_type_interface_init_declaration = vala_typeregister_function_real_get_type_interface_init_declaration;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_type_interface_init_statements = vala_typeregister_function_real_get_type_interface_init_statements;
	VALA_TYPEREGISTER_FUNCTION_CLASS (klass)->get_accessibility = vala_typeregister_function_real_get_accessibility;
}


static void vala_typeregister_function_instance_init (ValaTypeRegisterFunction * self) {
	ValaCCodeFragment* _tmp0_ = NULL;
	ValaCCodeFragment* _tmp1_ = NULL;
	ValaCCodeFragment* _tmp2_ = NULL;
	self->priv = VALA_TYPEREGISTER_FUNCTION_GET_PRIVATE (self);
	_tmp0_ = vala_ccode_fragment_new ();
	self->priv->source_declaration_fragment = _tmp0_;
	_tmp1_ = vala_ccode_fragment_new ();
	self->priv->declaration_fragment = _tmp1_;
	_tmp2_ = vala_ccode_fragment_new ();
	self->priv->definition_fragment = _tmp2_;
	self->ref_count = 1;
}


static void vala_typeregister_function_finalize (ValaTypeRegisterFunction* obj) {
	ValaTypeRegisterFunction * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_TYPE_TYPEREGISTER_FUNCTION, ValaTypeRegisterFunction);
	_vala_ccode_node_unref0 (self->priv->source_declaration_fragment);
	_vala_ccode_node_unref0 (self->priv->declaration_fragment);
	_vala_ccode_node_unref0 (self->priv->definition_fragment);
	_vala_code_context_unref0 (self->priv->_context);
}


/**
 * C function to register a type at runtime.
 */
GType vala_typeregister_function_get_type (void) {
	static volatile gsize vala_typeregister_function_type_id__volatile = 0;
	if (g_once_init_enter (&vala_typeregister_function_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { vala_value_typeregister_function_init, vala_value_typeregister_function_free_value, vala_value_typeregister_function_copy_value, vala_value_typeregister_function_peek_pointer, "p", vala_value_typeregister_function_collect_value, "p", vala_value_typeregister_function_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ValaTypeRegisterFunctionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_typeregister_function_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaTypeRegisterFunction), 0, (GInstanceInitFunc) vala_typeregister_function_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType vala_typeregister_function_type_id;
		vala_typeregister_function_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ValaTypeRegisterFunction", &g_define_type_info, &g_define_type_fundamental_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&vala_typeregister_function_type_id__volatile, vala_typeregister_function_type_id);
	}
	return vala_typeregister_function_type_id__volatile;
}


gpointer vala_typeregister_function_ref (gpointer instance) {
	ValaTypeRegisterFunction* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void vala_typeregister_function_unref (gpointer instance) {
	ValaTypeRegisterFunction* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		VALA_TYPEREGISTER_FUNCTION_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



